"""add row

Revision ID: 99f8b40e005b
Revises: b70a4097b735
Create Date: 2024-12-03 03:34:23.908727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '99f8b40e005b'
down_revision: Union[str, None] = 'b70a4097b735'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_name', sa.VARCHAR(), server_default='user', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_name')
    # ### end Alembic commands ###
